(()=>{
'use strict';
const BINANCE='https://data-api.binance.vision/api/v3';
const STREAM='wss://data-stream.binance.vision:443/stream?streams=';
const CG='https://api.coingecko.com/api/v3';
const COINS=[
 {symbol:'BTC',name:'Bitcoin',pair:'BTCUSDT',id:'bitcoin',tone:'orange'},
 {symbol:'ETH',name:'Ethereum',pair:'ETHUSDT',id:'ethereum',tone:'purple'},
 {symbol:'SOL',name:'Solana',pair:'SOLUSDT',id:'solana',tone:'green'},
 {symbol:'BNB',name:'BNB',pair:'BNBUSDT',id:'binancecoin',tone:'gold'},
 {symbol:'LINK',name:'Chainlink',pair:'LINKUSDT',id:'chainlink',tone:'blue'},
 {symbol:'XRP',name:'XRP',pair:'XRPUSDT',id:'ripple',tone:'blue'},
 {symbol:'ADA',name:'Cardano',pair:'ADAUSDT',id:'cardano',tone:'purple'},
 {symbol:'PI',name:'Pi Network',pair:null,id:'pi-network',tone:'violet'},
 {symbol:'SDA',name:'SDA',pair:null,id:null,tone:'gray'},
 {symbol:'UNI',name:'Uniswap',pair:'UNIUSDT',id:'uniswap',tone:'pink'}
];
const META=Object.fromEntries(COINS.map(c=>[c.symbol,c]));
const DATA=new Map();const HISTORY=new Map();let socket=null,reconnect=0,active=null,lastPaint=0;
const money=n=>{n=Number(n);if(!Number.isFinite(n))return '—';if(n>=1000)return n.toLocaleString('en-US',{maximumFractionDigits:2});if(n>=1)return n.toLocaleString('en-US',{maximumFractionDigits:4});return n.toLocaleString('en-US',{maximumFractionDigits:8})};
const pct=n=>Number.isFinite(Number(n))?`${Number(n)>=0?'+':''}${Number(n).toFixed(2)}%`:'—';
const getAlerts=()=>{try{return JSON.parse(localStorage.getItem('cryptopool-price-alerts')||'[]')}catch{return[]}};
const setAlerts=v=>localStorage.setItem('cryptopool-price-alerts',JSON.stringify(v));
function css(){if(document.getElementById('cp-v7-style'))return;const s=document.createElement('style');s.id='cp-v7-style';s.textContent=`.cp-v7-card{cursor:pointer}.cp-v7-card:hover{transform:translateY(-2px);border-color:#40536b}.cp-v7-live{display:inline-flex;align-items:center;gap:6px;color:#5ee6a3;font-weight:800}.cp-v7-dot{width:7px;height:7px;border-radius:50%;background:#54dfaa;box-shadow:0 0 9px #54dfaa}.cp-v7-na{color:#8793a4;font-size:10px}.cp-v7-modal{position:fixed;inset:0;z-index:100000;background:rgba(2,6,12,.84);display:flex;align-items:center;justify-content:center;padding:12px}.cp-v7-panel{width:min(960px,100%);max-height:94vh;overflow:auto;background:#0b121c;color:#eef4fa;border:1px solid #293b50;border-radius:20px;padding:18px;box-shadow:0 30px 90px #0009}.cp-v7-head{display:flex;justify-content:space-between;gap:12px}.cp-v7-head h2{margin:6px 0}.cp-v7-meta{color:#8794a6;font-size:11px}.cp-v7-close,.cp-v7-period,.cp-v7-add,.cp-v7-notify{background:#131e2b;color:#fff;border:1px solid #34465b;border-radius:9px;padding:9px 12px;cursor:pointer}.cp-v7-periods{display:flex;gap:7px;flex-wrap:wrap;margin:12px 0}.cp-v7-period.on{background:#2a4664}.cp-v7-chart{display:block;width:100%;height:320px;background:#071019;border-radius:14px}.cp-v7-source{margin-top:8px;color:#667588;font-size:10px}.cp-v7-alert{border-top:1px solid #243447;margin-top:16px;padding-top:14px}.cp-v7-grid{display:grid;grid-template-columns:1fr 1fr auto;gap:8px;margin-top:9px}.cp-v7-grid input,.cp-v7-grid select{min-width:0;background:#080f17;color:#fff;border:1px solid #34465b;border-radius:9px;padding:10px}.cp-v7-list{display:grid;gap:6px;margin-top:9px}.cp-v7-item{display:flex;justify-content:space-between;gap:10px;background:#111b27;border-radius:9px;padding:8px 10px}.cp-v7-item button{background:transparent;color:#ff8b9b;border:0;cursor:pointer}@media(max-width:600px){.cp-v7-panel{padding:13px}.cp-v7-chart{height:245px}.cp-v7-grid{grid-template-columns:1fr 1fr}.cp-v7-grid button{grid-column:1/-1}}`;document.head.appendChild(s)}
function seedHistory(sym,price){if(!HISTORY.has(sym))HISTORY.set(sym,[]);const h=HISTORY.get(sym);if(price&&h.at(-1)!==price){h.push(price);if(h.length>240)h.shift()}}
async function load(){
 let binanceOk=false;
 try{const pairs=COINS.filter(c=>c.pair).map(c=>c.pair);const r=await fetch(`${BINANCE}/ticker/24hr?symbols=${encodeURIComponent(JSON.stringify(pairs))}`,{cache:'no-store'});if(!r.ok)throw Error();for(const x of await r.json()){DATA.set(x.symbol,{price:+x.lastPrice,change:+x.priceChangePercent,source:'Binance'});const c=COINS.find(c=>c.pair===x.symbol);if(c)seedHistory(c.symbol,+x.lastPrice)}binanceOk=true}catch{}
 try{const ids=COINS.filter(c=>c.id).map(c=>c.id);const r=await fetch(`${CG}/simple/price?ids=${ids.join(',')}&vs_currencies=usd&include_24hr_change=true`,{cache:'no-store'});if(r.ok){const j=await r.json();for(const c of COINS.filter(c=>c.id&&!c.pair)){const d=j[c.id];if(d?.usd){DATA.set(c.symbol,{price:+d.usd,change:+(d.usd_24h_change||0),source:'CoinGecko'});seedHistory(c.symbol,+d.usd)}}}}catch{}
 if(!DATA.has('SDA'))DATA.set('SDA',{price:null,change:null,source:'Chưa xác định nguồn giá trực tiếp'});
 paint();return binanceOk;
}
function connect(){clearTimeout(reconnect);try{socket?.close()}catch{}const pairs=COINS.filter(c=>c.pair).map(c=>`${c.pair.toLowerCase()}@miniTicker`).join('/');try{socket=new WebSocket(STREAM+pairs);socket.onmessage=e=>{try{const x=JSON.parse(e.data).data;if(!x?.s)return;const c=COINS.find(c=>c.pair===x.s);if(!c)return;const close=+x.c,open=+x.o;DATA.set(x.s,{price:close,change:open?((close-open)/open)*100:0,source:'Binance live'});seedHistory(c.symbol,close);paint();checkAlerts(c.symbol)}catch{}};socket.onerror=()=>{try{socket.close()}catch{}};socket.onclose=()=>{reconnect=setTimeout(connect,5000)}}catch{reconnect=setTimeout(connect,5000)}}
function card(c){const d=DATA.get(c.symbol),live=Number.isFinite(d?.price);return `<article class="asset-card cp-v7-card" data-cp-symbol="${c.symbol}" tabindex="0"><div class="asset-head"><div class="asset-icon ${c.tone}">${c.symbol[0]}</div><div><strong>${c.symbol}</strong><span>${c.name}</span></div><span class="change ${d?.change>=0?'positive':'negative'}">${pct(d?.change)}</span></div><div class="asset-price">${live?'$'+money(d.price):'—'}</div><div class="spark"><span/><span/><span/><span/><span/><span/><span/></div></article>`}
function paint(){const now=Date.now();if(now-lastPaint<180)return;lastPaint=now;const grid=document.querySelector('.asset-grid');if(grid){const sig=grid.dataset.cpSig||'';const next=COINS.map(c=>c.symbol).join(',');if(sig!==next){grid.innerHTML=COINS.map(card).join('');grid.dataset.cpSig=next}}const table=document.querySelector('.market-table');if(table){table.innerHTML=`<div class="market-row header"><span>Asset</span><span>Price</span><span>24h</span><span>Status</span></div>`+COINS.map(c=>{const d=DATA.get(c.symbol),live=Number.isFinite(d?.price);return `<div class="market-row cp-v7-card" data-cp-symbol="${c.symbol}" tabindex="0"><span class="asset-cell"><b>${c.symbol}</b><small>${c.name}</small></span><strong>${live?'$'+money(d.price):'—'}</strong><span class="${d?.change>=0?'positive':'negative'}">${pct(d?.change)}</span><span class="table-status">${live?'<span class="cp-v7-live"><i class="cp-v7-dot"></i>LIVE</span>':'<span class="cp-v7-na">Nguồn chưa khả dụng</span>'}</span></div>`}).join('')}}
function open(sym){const c=META[sym];if(!c)return;css();active=sym;let m=document.getElementById('cp-v7-modal');if(!m){m=document.createElement('div');m.id='cp-v7-modal';m.className='cp-v7-modal';m.innerHTML=`<div class="cp-v7-panel" role="dialog" aria-modal="true"><div class="cp-v7-head"><div><small class="cp-v7-live"><i class="cp-v7-dot"></i> LIVE MARKET</small><h2 id="cp-v7-title"></h2><div id="cp-v7-meta" class="cp-v7-meta"></div><div id="cp-v7-source" class="cp-v7-source"></div></div><button class="cp-v7-close" id="cp-v7-close">Đóng</button></div><canvas class="cp-v7-chart" id="cp-v7-chart"></canvas><div class="cp-v7-periods">${[['1m','1P'],['15m','15P'],['1h','1H'],['4h','4H'],['12h','12H'],['1d','1D'],['7d','7D']].map((x,i)=>`<button class="cp-v7-period ${i===2?'on':''}" data-period="${x[0]}">${x[1]}</button>`).join('')}</div><div class="cp-v7-alert"><b>🔔 Cảnh báo giá</b><div style="margin-top:9px"><button class="cp-v7-notify" id="cp-v7-notify">Bật thông báo</button></div><div class="cp-v7-grid"><input id="cp-v7-price" inputmode="decimal" placeholder="Giá mục tiêu"><select id="cp-v7-op"><option value="above">Khi giá ≥</option><option value="below">Khi giá ≤</option></select><button class="cp-v7-add" id="cp-v7-add">Thêm cảnh báo</button></div><div id="cp-v7-list" class="cp-v7-list"></div></div></div>`;document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m)close()});document.getElementById('cp-v7-close').onclick=close;document.getElementById('cp-v7-notify').onclick=async()=>{if('Notification'in window&&Notification.permission==='default')await Notification.requestPermission()};document.getElementById('cp-v7-add').onclick=()=>addAlert(active);m.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>chart(active,b.dataset.period))}const d=DATA.get(sym)||{};document.getElementById('cp-v7-title').textContent=`${c.name} (${c.symbol})`;document.getElementById('cp-v7-meta').textContent=Number.isFinite(d.price)?'$'+money(d.price)+' · '+pct(d.change):'Giá trực tiếp chưa khả dụng';document.getElementById('cp-v7-source').textContent=d.source||'Nguồn dữ liệu';m.style.display='flex';showAlerts(sym);chart(sym,'1h')}
function close(){const m=document.getElementById('cp-v7-modal');if(m)m.style.display='none';active=null}
async function chart(sym,period){document.querySelectorAll('.cp-v7-period').forEach(b=>b.classList.toggle('on',b.dataset.period===period));const c=META[sym],canvas=document.getElementById('cp-v7-chart');if(!canvas)return;if(!c.pair){const h=HISTORY.get(sym)||[];draw(h.length?h:[]);return}const cfg={ '1m':['1m',120], '15m':['15m',120], '1h':['1h',120], '4h':['4h',120], '12h':['12h',120], '1d':['1d',90], '7d':['4h',42] }[period]||['1h',120];try{const r=await fetch(`${BINANCE}/klines?symbol=${c.pair}&interval=${cfg[0]}&limit=${cfg[1]}`,{cache:'no-store'});if(!r.ok)throw Error();draw((await r.json()).map(x=>+x[4]))}catch{draw(HISTORY.get(sym)||[])} }
function draw(v){const c=document.getElementById('cp-v7-chart');if(!c)return;const dpr=Math.max(1,devicePixelRatio||1),w=c.clientWidth||800,h=c.clientHeight||320;c.width=w*dpr;c.height=h*dpr;const x=c.getContext('2d');x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,w,h);if(!v.length){x.fillStyle='#8793a4';x.font='14px system-ui';x.fillText('Biểu đồ chưa có dữ liệu cho tài sản này.',18,32);return}const lo=Math.min(...v),hi=Math.max(...v),pad=(hi-lo||Math.max(hi,1)*.01)*.12;x.beginPath();v.forEach((p,i)=>{const X=20+i*(w-40)/Math.max(1,v.length-1),Y=h-26-(p-(lo-pad))*(h-54)/(hi-lo+2*pad);i?x.lineTo(X,Y):x.moveTo(X,Y)});x.strokeStyle='#5ee6a3';x.lineWidth=2;x.stroke();x.fillStyle='#8793a4';x.font='11px system-ui';x.fillText('$'+money(hi),20,15);x.fillText('$'+money(lo),20,h-8);x.fillText('$'+money(v.at(-1)),w-110,15)}
function showAlerts(sym){const e=document.getElementById('cp-v7-list');if(!e)return;const a=getAlerts().filter(x=>x.symbol===sym);e.innerHTML=a.length?a.map(x=>`<div class="cp-v7-item"><span>${x.op==='above'?'≥':'≤'} $${money(x.price)}</span><button data-rm="${x.id}">Xóa</button></div>`).join(''):'<small>Chưa có cảnh báo.</small>';e.querySelectorAll('[data-rm]').forEach(b=>b.onclick=()=>{setAlerts(getAlerts().filter(x=>String(x.id)!==b.dataset.rm));showAlerts(sym)})}
function addAlert(sym){const p=Number(document.getElementById('cp-v7-price')?.value),op=document.getElementById('cp-v7-op')?.value;if(!(p>0))return;const a=getAlerts();a.push({id:Date.now(),symbol:sym,op,price:p});setAlerts(a);document.getElementById('cp-v7-price').value='';showAlerts(sym)}
function checkAlerts(sym){const d=DATA.get(META[sym]?.pair||'');if(!d?.price)return;const list=getAlerts();const fired=new Set(JSON.parse(sessionStorage.getItem('cp-v7-fired')||'[]'));let changed=false;for(const a of list){if(a.symbol!==sym||fired.has(a.id))continue;const hit=a.op==='above'?d.price>=a.price:d.price<=a.price;if(hit){fired.add(a.id);changed=true;const text=`${sym}: giá ${a.op==='above'?'≥':'≤'} $${money(a.price)}`;if('Notification'in window&&Notification.permission==='granted')new Notification('CryptoPool — Cảnh báo giá',{body:text});if(navigator.vibrate)try{navigator.vibrate([120,60,120])}catch{}}}if(changed)sessionStorage.setItem('cp-v7-fired',JSON.stringify([...fired]))}
function init(){css();document.addEventListener('click',e=>{const t=e.target.closest?.('[data-cp-symbol]');if(t)open(t.dataset.cpSymbol)});document.addEventListener('keydown',e=>{const t=e.target.closest?.('[data-cp-symbol]');if(t&&(e.key==='Enter'||e.key===' ')){e.preventDefault();open(t.dataset.cpSymbol)}if(e.key==='Escape')close()});load();connect();setInterval(load,30000);setInterval(paint,2000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
