(()=>{
'use strict';
const BINANCE='https://data-api.binance.vision/api/v3';
const STREAM='wss://data-stream.binance.vision:443/stream?streams=';
const CG='https://api.coingecko.com/api/v3';
const COINS=[
 {s:'BTC',n:'Bitcoin',p:'BTCUSDT',id:'bitcoin',t:'orange'},
 {s:'ETH',n:'Ethereum',p:'ETHUSDT',id:'ethereum',t:'purple'},
 {s:'SOL',n:'Solana',p:'SOLUSDT',id:'solana',t:'green'},
 {s:'BNB',n:'BNB',p:'BNBUSDT',id:'binancecoin',t:'gold'},
 {s:'LINK',n:'Chainlink',p:'LINKUSDT',id:'chainlink',t:'blue'},
 {s:'XRP',n:'XRP',p:'XRPUSDT',id:'ripple',t:'blue'},
 {s:'ADA',n:'Cardano',p:'ADAUSDT',id:'cardano',t:'purple'},
 {s:'PI',n:'Pi Network',p:null,id:'pi-network',t:'violet'},
 {s:'SDA',n:'SDA',p:null,id:null,t:'gray'},
 {s:'UNI',n:'Uniswap',p:'UNIUSDT',id:'uniswap',t:'pink'}
];
const M=Object.fromEntries(COINS.map(c=>[c.s,c]));
const D=new Map(),H=new Map();let ws=null,retry=0,active=null,modal=null,lastPaint=0;
const fmt=n=>{n=Number(n);if(!Number.isFinite(n))return '—';if(n>=1000)return n.toLocaleString('en-US',{maximumFractionDigits:2});if(n>=1)return n.toLocaleString('en-US',{maximumFractionDigits:4});return n.toLocaleString('en-US',{maximumFractionDigits:8})};
const change=n=>Number.isFinite(Number(n))?`${Number(n)>=0?'+':''}${Number(n).toFixed(2)}%`:'—';
const live=d=>Number.isFinite(d?.price);
function style(){if(document.getElementById('cp-v8-style'))return;const s=document.createElement('style');s.id='cp-v8-style';s.textContent=`.cp-v8-click{cursor:pointer}.cp-v8-click:hover{transform:translateY(-2px)}.cp-v8-live{display:inline-flex;align-items:center;gap:6px;color:#5ee6a3;font-weight:800}.cp-v8-dot{width:7px;height:7px;border-radius:50%;background:#54dfaa;box-shadow:0 0 9px #54dfaa}.cp-v8-na{color:#8793a4;font-size:10px}.cp-v8-modal{position:fixed;inset:0;z-index:100000;background:rgba(2,6,12,.86);display:flex;align-items:center;justify-content:center;padding:12px}.cp-v8-panel{width:min(960px,100%);max-height:94vh;overflow:auto;background:#0b121c;color:#eef4fa;border:1px solid #293b50;border-radius:20px;padding:18px;box-shadow:0 30px 90px #0009}.cp-v8-head{display:flex;justify-content:space-between;gap:12px}.cp-v8-head h2{margin:6px 0}.cp-v8-meta,.cp-v8-source{color:#8794a6;font-size:11px}.cp-v8-source{margin-top:5px}.cp-v8-close,.cp-v8-period{background:#131e2b;color:#fff;border:1px solid #34465b;border-radius:9px;padding:9px 12px;cursor:pointer}.cp-v8-period.on{background:#2a4664}.cp-v8-periods{display:flex;gap:7px;flex-wrap:wrap;margin:12px 0}.cp-v8-chart{display:block;width:100%;height:320px;background:#071019;border-radius:14px}.cp-v8-note{margin-top:10px;color:#8794a6;font-size:11px}.cp-v8-badge{display:inline-flex;margin-left:8px;padding:4px 7px;border:1px solid #314255;border-radius:999px;font-size:9px;font-weight:800}@media(max-width:600px){.cp-v8-panel{padding:13px}.cp-v8-chart{height:245px}.cp-v8-period{padding:8px 10px;font-size:11px}}`;document.head.appendChild(s)}
function history(s,p){if(!H.has(s))H.set(s,[]);const a=H.get(s);if(Number.isFinite(p)&&a.at(-1)!==p){a.push(p);if(a.length>500)a.shift()}}
async function prices(){
 try{const ps=COINS.filter(c=>c.p).map(c=>c.p);const r=await fetch(`${BINANCE}/ticker/24hr?symbols=${encodeURIComponent(JSON.stringify(ps))}`,{cache:'no-store'});if(r.ok)for(const x of await r.json()){const c=COINS.find(z=>z.p===x.symbol);if(c){const p=+x.lastPrice;D.set(c.s,{price:p,change:+x.priceChangePercent,source:'Binance'});history(c.s,p)}}}catch{}
 try{const ids=COINS.filter(c=>c.id).map(c=>c.id).join(',');const r=await fetch(`${CG}/simple/price?ids=${ids}&vs_currencies=usd&include_24hr_change=true`,{cache:'no-store'});if(r.ok){const j=await r.json();for(const c of COINS.filter(z=>z.id)){const x=j[c.id];if(x?.usd&&(!D.has(c.s)||!c.p)){D.set(c.s,{price:+x.usd,change:+(x.usd_24h_change||0),source:'CoinGecko'});history(c.s,+x.usd)}}}}catch{}
 D.set('SDA',D.get('SDA')||{price:null,change:null,source:'Chưa xác định nguồn giá trực tiếp'});paint();
}
function connect(){clearTimeout(retry);try{ws?.close()}catch{}const streams=COINS.filter(c=>c.p).map(c=>`${c.p.toLowerCase()}@miniTicker`).join('/');if(!streams)return;try{ws=new WebSocket(STREAM+streams);ws.onmessage=e=>{try{const x=JSON.parse(e.data).data;if(!x?.s)return;const c=COINS.find(z=>z.p===x.s);if(!c)return;const p=+x.c,o=+x.o;D.set(c.s,{price:p,change:o?((p-o)/o)*100:0,source:'Binance live'});history(c.s,p);paint()}catch{}};ws.onerror=()=>{try{ws.close()}catch{}};ws.onclose=()=>{retry=setTimeout(connect,5000)}}catch{retry=setTimeout(connect,5000)}}
function card(c){const d=D.get(c.s);return `<article class="asset-card cp-v8-click" data-cp-symbol="${c.s}" tabindex="0"><div class="asset-head"><div class="asset-icon ${c.t}">${c.s[0]}</div><div><strong>${c.s}</strong><span>${c.n}</span></div><span class="change ${Number(d?.change)>=0?'positive':'negative'}">${change(d?.change)}</span></div><div class="asset-price">${live(d)?'$'+fmt(d.price):'—'}</div><div class="spark"><span/><span/><span/><span/><span/><span/><span/></div></article>`}
function paint(){const now=Date.now();if(now-lastPaint<250)return;lastPaint=now;const q=(document.querySelector('.search input')?.value||'').trim().toLowerCase();const list=COINS.filter(c=>`${c.s} ${c.n}`.toLowerCase().includes(q));const grid=document.querySelector('.asset-grid');if(grid){const sig=list.map(c=>c.s).join(',')+'|'+COINS.map(c=>D.get(c.s)?.price??'').join(',');if(grid.dataset.cpSig!==sig){grid.innerHTML=list.map(card).join('');grid.dataset.cpSig=sig}}const table=document.querySelector('.market-table');if(table){table.innerHTML=`<div class="market-row header"><span>Asset</span><span>Price</span><span>24h</span><span>Status</span></div>`+list.map(c=>{const d=D.get(c.s);return `<div class="market-row cp-v8-click" data-cp-symbol="${c.s}" tabindex="0"><span class="asset-cell"><b>${c.s}</b><small>${c.n}</small></span><strong>${live(d)?'$'+fmt(d.price):'—'}</strong><span class="${Number(d?.change)>=0?'positive':'negative'}">${change(d?.change)}</span><span class="table-status">${live(d)?'<span class="cp-v8-live"><i class="cp-v8-dot"></i>LIVE</span>':'<span class="cp-v8-na">Nguồn chưa khả dụng</span>'}</span></div>`}).join('')}}const status=document.querySelector('.toolbar .muted');if(status){const n=COINS.filter(c=>live(D.get(c.s))).length;status.innerHTML=`<span class="cp-v8-live"><i class="cp-v8-dot"></i> LIVE · ${n}/${COINS.length}</span>`}const stat=document.querySelector('.stats-row div:nth-child(2) strong');if(stat)stat.innerHTML=`10 <small>crypto assets</small>`}
function modalUI(){if(modal)return;style();modal=document.createElement('div');modal.className='cp-v8-modal';modal.innerHTML=`<div class="cp-v8-panel" role="dialog" aria-modal="true"><div class="cp-v8-head"><div><small class="cp-v8-live"><i class="cp-v8-dot"></i> LIVE MARKET</small><h2 id="cp-v8-title"></h2><div id="cp-v8-meta" class="cp-v8-meta"></div><div id="cp-v8-source" class="cp-v8-source"></div></div><button class="cp-v8-close" type="button">Đóng</button></div><canvas id="cp-v8-chart" class="cp-v8-chart"></canvas><div class="cp-v8-periods">${[['1m','1P'],['15m','15P'],['1h','1H'],['4h','4H'],['12h','12H'],['1d','1D'],['7d','7D']].map((x,i)=>`<button type="button" class="cp-v8-period ${i===2?'on':''}" data-period="${x[0]}">${x[1]}</button>`).join('')}</div><div id="cp-v8-note" class="cp-v8-note"></div></div>`;document.body.appendChild(modal);modal.querySelector('.cp-v8-close').onclick=()=>{modal.style.display='none';active=null};modal.addEventListener('click',e=>{if(e.target===modal){modal.style.display='none';active=null}});modal.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>loadChart(active,b.dataset.period))}
function open(s){const c=M[s];if(!c)return;modalUI();active=s;const d=D.get(s)||{};document.getElementById('cp-v8-title').textContent=`${c.n} (${c.s})`;document.getElementById('cp-v8-meta').textContent=live(d)?`$${fmt(d.price)} · ${change(d.change)}`:'Giá trực tiếp chưa khả dụng';document.getElementById('cp-v8-source').textContent=d.source||'Nguồn dữ liệu';document.getElementById('cp-v8-note').textContent=c.s==='SDA'?'Chưa xác định được nguồn giá trực tiếp đáng tin cậy cho SDA — không hiển thị giá giả.':'';modal.style.display='flex';loadChart(s,'1h')}
function draw(v){const c=document.getElementById('cp-v8-chart');if(!c)return;const dpr=Math.max(1,devicePixelRatio||1),w=c.clientWidth||800,h=c.clientHeight||320;c.width=w*dpr;c.height=h*dpr;const x=c.getContext('2d');x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,w,h);if(!v?.length){x.fillStyle='#8793a4';x.font='14px system-ui';x.fillText('Biểu đồ chưa có dữ liệu cho tài sản này.',18,32);return}const lo=Math.min(...v),hi=Math.max(...v),pad=(hi-lo||Math.max(hi,1)*.01)*.12;x.beginPath();v.forEach((p,i)=>{const X=20+i*(w-40)/Math.max(1,v.length-1),Y=h-26-(p-(lo-pad))*(h-54)/(hi-lo+2*pad);i?x.lineTo(X,Y):x.moveTo(X,Y)});x.strokeStyle='#5ee6a3';x.lineWidth=2;x.stroke();x.fillStyle='#8793a4';x.font='11px system-ui';x.fillText('$'+fmt(hi),20,15);x.fillText('$'+fmt(lo),20,h-8);x.fillText('$'+fmt(v.at(-1)),w-110,15)}
async function loadChart(s,period){if(!modal)return;modal.querySelectorAll('.cp-v8-period').forEach(b=>b.classList.toggle('on',b.dataset.period===period));const c=M[s];if(!c||s==='SDA'){draw(H.get(s)||[]);return}const cfg={'1m':['1m',120],'15m':['15m',120],'1h':['1h',120],'4h':['4h',120],'12h':['12h',120],'1d':['1d',90],'7d':['4h',42]}[period]||['1h',120];try{let values=[];if(c.p){const r=await fetch(`${BINANCE}/klines?symbol=${c.p}&interval=${cfg[0]}&limit=${cfg[1]}`,{cache:'no-store'});if(!r.ok)throw Error();values=(await r.json()).map(x=>+x[4])}else if(c.id){const days=period==='1d'?1:period==='7d'?7:1;const r=await fetch(`${CG}/coins/${c.id}/market_chart?vs_currency=usd&days=${days}`,{cache:'no-store'});if(!r.ok)throw Error();values=(await r.json()).prices.map(x=>+x[1]).slice(-cfg[1])}draw(values)}catch{draw(H.get(s)||[])}}
function init(){style();document.addEventListener('click',e=>{const t=e.target.closest?.('[data-cp-symbol]');if(t)open(t.dataset.cpSymbol)});document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.closest?.('[data-cp-symbol]')){e.preventDefault();open(e.target.closest('[data-cp-symbol]').dataset.cpSymbol)}if(e.key==='Escape'&&modal){modal.style.display='none';active=null}});prices();connect();setInterval(prices,30000);setInterval(paint,500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
