(()=>{
'use strict';
const REST='https://data-api.binance.vision/api/v3', WS='wss://data-stream.binance.vision:443/stream?streams=', CG='https://api.coingecko.com/api/v3';
const COINS=[['BTC','Bitcoin','BTCUSDT','bitcoin'],['ETH','Ethereum','ETHUSDT','ethereum'],['BNB','BNB','BNBUSDT','binancecoin'],['SOL','Solana','SOLUSDT','solana'],['XRP','XRP','XRPUSDT','ripple'],['ADA','Cardano','ADAUSDT','cardano'],['DOGE','Dogecoin','DOGEUSDT','dogecoin'],['USDC','USD Coin','USDCUSDT','usd-coin'],['LINK','Chainlink','LINKUSDT','chainlink'],['UNI','Uniswap','UNIUSDT','uniswap'],['AVAX','Avalanche','AVAXUSDT','avalanche-2'],['DOT','Polkadot','DOTUSDT','polkadot']];
const META=Object.fromEntries(COINS.map(c=>[c[0],{symbol:c[0],name:c[1],pair:c[2],id:c[3]}]));
const DATA=new Map();let socket=null,reconnectTimer=null,currentSymbol=null,lastPaint=0;
const money=n=>{n=Number(n);if(!Number.isFinite(n))return '—';if(n>=1000)return n.toLocaleString('en-US',{maximumFractionDigits:2});if(n>=1)return n.toLocaleString('en-US',{maximumFractionDigits:4});return n.toLocaleString('en-US',{maximumFractionDigits:6})};
const pct=n=>`${Number(n)>=0?'+':''}${(Number(n)||0).toFixed(2)}%`;
const getAlerts=()=>{try{return JSON.parse(localStorage.getItem('cryptopool-price-alerts')||'[]')}catch{return[]}};
const setAlerts=a=>localStorage.setItem('cryptopool-price-alerts',JSON.stringify(a));
function injectCss(){if(document.getElementById('cp-live-v6'))return;const s=document.createElement('style');s.id='cp-live-v6';s.textContent=`.cp-click{cursor:pointer}.cp-click:focus{outline:2px solid #4f8cff;outline-offset:2px}.cp-live{color:#38e58b;font-weight:800}.cp-live-dot{display:inline-block;width:7px;height:7px;border-radius:50%;background:#38e58b;box-shadow:0 0 8px #38e58b;margin-right:5px}.cp-market-live{display:inline-flex;align-items:center;gap:5px;color:#58dca5;font-weight:800}.cp-modal{position:fixed;inset:0;z-index:100000;background:rgba(2,6,12,.82);display:flex;align-items:center;justify-content:center;padding:12px}.cp-panel{width:min(920px,100%);max-height:92vh;overflow:auto;background:#0b121c;color:#eef4fa;border:1px solid #26384c;border-radius:20px;padding:18px;box-shadow:0 24px 80px #0008}.cp-top{display:flex;justify-content:space-between;gap:12px}.cp-top h2{margin:5px 0}.cp-close,.cp-period,.cp-add,.cp-notify{background:#131e2b;color:#fff;border:1px solid #34465b;border-radius:9px;padding:9px 12px;cursor:pointer}.cp-periods{display:flex;gap:7px;flex-wrap:wrap;margin:10px 0}.cp-period.on{background:#2a4664}.cp-chart{display:block;width:100%;height:300px;background:#071019;border-radius:14px}.cp-alert{border-top:1px solid #243447;margin-top:16px;padding-top:14px}.cp-alert-grid{display:grid;grid-template-columns:1fr 1fr auto;gap:8px;margin-top:9px}.cp-alert-grid input,.cp-alert-grid select{min-width:0;background:#080f17;color:#fff;border:1px solid #34465b;border-radius:9px;padding:10px}.cp-alert-list{display:grid;gap:6px;margin-top:9px}.cp-alert-item{display:flex;justify-content:space-between;gap:10px;background:#111b27;border-radius:9px;padding:8px 10px}.cp-alert-item button{background:transparent;color:#ff8b9b;border:0;cursor:pointer}.cp-alert-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:9px}@media(max-width:600px){.cp-panel{padding:13px;border-radius:16px}.cp-chart{height:235px}.cp-alert-grid{grid-template-columns:1fr 1fr}.cp-alert-grid button{grid-column:1/-1}}`;document.head.appendChild(s)}
function data(sym){return META[sym]&&DATA.get(META[sym].pair)}
async function loadPrices(){let ok=false;try{const symbols=JSON.stringify(COINS.map(c=>c[2]));const r=await fetch(`${REST}/ticker/24hr?symbols=${encodeURIComponent(symbols)}`,{cache:'no-store'});if(!r.ok)throw Error();(await r.json()).forEach(x=>DATA.set(x.symbol,{price:+x.lastPrice,change:+x.priceChangePercent,source:'Binance'}));ok=true}catch{}if(!ok)try{const r=await fetch(`${CG}/simple/price?ids=${COINS.map(c=>c[3]).join(',')}&vs_currencies=usd&include_24hr_change=true`,{cache:'no-store'});if(!r.ok)throw Error();const j=await r.json();COINS.forEach(c=>{const d=j[c[3]];if(d?.usd)DATA.set(c[2],{price:+d.usd,change:+(d.usd_24h_change||0),source:'CoinGecko'})});ok=true}catch{}paint();return ok}
function connect(){clearTimeout(reconnectTimer);try{socket?.close()}catch{}try{socket=new WebSocket(WS+COINS.map(c=>`${c[2].toLowerCase()}@miniTicker`).join('/'));socket.onmessage=e=>{try{const x=JSON.parse(e.data).data;if(!x?.s)return;const old=DATA.get(x.s)||{};const open=Number(x.o),close=Number(x.c);DATA.set(x.s,{...old,price:close,change:open?((close-open)/open)*100:old.change,source:'Binance live'});paint();checkAlerts(x.s)}catch{}};socket.onerror=()=>{try{socket.close()}catch{}};socket.onclose=()=>{reconnectTimer=setTimeout(connect,5000)}}catch{reconnectTimer=setTimeout(connect,5000)}}
function paint(){const now=Date.now();if(now-lastPaint<250)return;lastPaint=now;const liveCount=[...DATA.values()].filter(d=>d?.price).length;document.querySelectorAll('.asset-card').forEach(card=>{const sym=card.querySelector('strong')?.textContent?.trim().toUpperCase(),d=data(sym);if(!d?.price)return;const p=card.querySelector('.asset-price'),q=card.querySelector('.change');if(p)p.textContent='$'+money(d.price);if(q){q.textContent=pct(d.change);q.className='change '+(d.change>=0?'positive':'negative')}card.classList.add('cp-click');card.dataset.cpSymbol=sym});document.querySelectorAll('.market-table .market-row:not(.header)').forEach(row=>{const sym=row.querySelector('.asset-cell b')?.textContent?.trim().toUpperCase(),d=data(sym);if(!d?.price)return;row.classList.add('cp-click');row.dataset.cpSymbol=sym;const c=row.children;if(c[1])c[1].innerHTML='<strong>$'+money(d.price)+'</strong>';if(c[2])c[2].innerHTML='<span class="'+(d.change>=0?'positive':'negative')+'">'+pct(d.change)+'</span>';if(c[3])c[3].innerHTML='<span class="cp-market-live"><i class="cp-live-dot"></i>LIVE</span>'});document.querySelectorAll('.muted').forEach(el=>{if(el.textContent.trim()==='Dữ liệu demo')el.innerHTML='<span class="cp-market-live"><i class="cp-live-dot"></i>LIVE · '+liveCount+'/'+COINS.length+'</span>'});const meta=document.getElementById('cp-meta');if(meta&&currentSymbol){const d=data(currentSymbol);if(d)meta.textContent='$'+money(d.price)+' · '+pct(d.change)+' · '+d.source}}
function open(sym){if(!META[sym])return;injectCss();currentSymbol=sym;let modal=document.getElementById('cp-modal');if(!modal){modal=document.createElement('div');modal.id='cp-modal';modal.className='cp-modal';modal.innerHTML=`<div class="cp-panel" role="dialog" aria-modal="true"><div class="cp-top"><div><small class="cp-live">● LIVE MARKET</small><h2 id="cp-title"></h2><p id="cp-meta"></p></div><button class="cp-close" id="cp-close">Đóng</button></div><canvas class="cp-chart" id="cp-chart"></canvas><div class="cp-periods"><button class="cp-period" data-period="1h">1H</button><button class="cp-period on" data-period="24h">24H</button><button class="cp-period" data-period="7d">7D</button><button class="cp-period" data-period="30d">30D</button></div><div class="cp-alert"><b>🔔 Cảnh báo giá</b><div class="cp-alert-actions"><button class="cp-notify" id="cp-notify">Bật thông báo</button></div><div class="cp-alert-grid"><input id="cp-price" inputmode="decimal" placeholder="Giá mục tiêu"><select id="cp-op"><option value="above">Khi giá ≥</option><option value="below">Khi giá ≤</option></select><button class="cp-add" id="cp-add">Thêm cảnh báo</button></div><div id="cp-alert-list" class="cp-alert-list"></div></div></div>`;document.body.appendChild(modal);modal.addEventListener('click',e=>{if(e.target===modal)close()});document.getElementById('cp-close').onclick=close;document.getElementById('cp-notify').onclick=async()=>{if('Notification' in window&&Notification.permission==='default')await Notification.requestPermission();};document.getElementById('cp-add').onclick=()=>addAlert(sym);modal.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>drawChart(sym,b.dataset.period))}const m=META[sym],d=data(sym)||{};document.getElementById('cp-title').textContent=`${m.name} (${m.symbol})`;document.getElementById('cp-meta').textContent=d.price?'$'+money(d.price)+' · '+pct(d.change)+' · '+(d.source||'Live'):'Đang tải…';modal.style.display='flex';showAlerts(sym);drawChart(sym,'24h')}
function close(){const m=document.getElementById('cp-modal');if(m)m.style.display='none';currentSymbol=null}
async function drawChart(sym,period){const m=META[sym],cfg={1h:['1m',60],24h:['15m',96],7d:['1h',168],30d:['4h',180]}[period]||['15m',96];document.querySelectorAll('.cp-period').forEach(b=>b.classList.toggle('on',b.dataset.period===period));try{const r=await fetch(`${REST}/klines?symbol=${m.pair}&interval=${cfg[0]}&limit=${cfg[1]}`,{cache:'no-store'});if(!r.ok)throw Error();draw((await r.json()).map(x=>+x[4]))}catch{draw([])}}
function draw(values){const c=document.getElementById('cp-chart');if(!c)return;const ratio=Math.max(1,devicePixelRatio||1),w=c.clientWidth||800,h=c.clientHeight||300;c.width=w*ratio;c.height=h*ratio;const x=c.getContext('2d');x.setTransform(ratio,0,0,ratio,0,0);x.clearRect(0,0,w,h);if(!values.length){x.fillStyle='#8b97a5';x.font='14px system-ui';x.fillText('Không tải được biểu đồ. Thử lại sau.',18,30);return}let lo=Math.min(...values),hi=Math.max(...values),pad=(hi-lo||Math.max(hi,1)*.01)*.1;lo-=pad;hi+=pad;x.beginPath();values.forEach((p,i)=>{const X=20+i*(w-40)/Math.max(1,values.length-1),Y=h-25-(p-lo)*(h-50)/(hi-lo);i?x.lineTo(X,Y):x.moveTo(X,Y)});x.strokeStyle='#5ee6a3';x.lineWidth=2;x.stroke();x.fillStyle='#8b97a5';x.font='11px system-ui';x.fillText('$'+money(hi),20,14);x.fillText('$'+money(lo),20,h-7);x.fillText('$'+money(values.at(-1)),w-105,14)}
function showAlerts(sym){const el=document.getElementById('cp-alert-list');if(!el)return;const list=getAlerts().filter(a=>a.symbol===sym);el.innerHTML=list.length?list.map(a=>`<div class="cp-alert-item"><span>${a.op==='above'?'≥':'≤'} $${money(a.price)}</span><button data-remove="${a.id}">Xóa</button></div>`).join(''):'<small>Chưa có cảnh báo.</small>';el.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{setAlerts(getAlerts().filter(a=>String(a.id)!==b.dataset.remove));showAlerts(sym)})}
function addAlert(sym){const price=Number(document.getElementById('cp-price')?.value),op=document.getElementById('cp-op')?.value;if(!(price>0))return;const a=getAlerts();a.push({id:Date.now(),symbol:sym,op,price});setAlerts(a);document.getElementById('cp-price').value='';showAlerts(sym);checkAlerts(META[sym].pair)}
function checkAlerts(pair){const d=DATA.get(pair);if(!d?.price)return;const sym=COINS.find(c=>c[2]===pair)?.[0];if(!sym)return;const list=getAlerts(),fired=new Set(JSON.parse(sessionStorage.getItem('cp-fired-alerts')||'[]'));let changed=false;list.forEach(a=>{if(a.symbol!==sym||fired.has(a.id))return;const hit=a.op==='above'?d.price>=a.price:d.price<=a.price;if(hit){fired.add(a.id);changed=true;notify(a,d.price)}});if(changed)sessionStorage.setItem('cp-fired-alerts',JSON.stringify([...fired]))}
function notify(a,price){const text=`${a.symbol}: giá đã ${a.op==='above'?'tăng tới':'giảm tới'} $${money(price)}`;if('Notification' in window&&Notification.permission==='granted')new Notification('CryptoPool — Cảnh báo giá',{body:text});if(navigator.vibrate)try{navigator.vibrate([120,60,120])}catch{};const m=document.getElementById('cp-meta');if(m&&currentSymbol===a.symbol)m.textContent=text+' · LIVE'}
function init(){injectCss();document.addEventListener('click',e=>{const target=e.target.closest?.('[data-cp-symbol]');if(target?.dataset.cpSymbol)open(target.dataset.cpSymbol)});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});loadPrices();connect();setInterval(loadPrices,30000);setInterval(paint,2000);paint()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
