import React, { useEffect, useMemo, useState } from "react";
import ReactDOM from "react-dom/client";
import { createAppKit, AppKitButton, useAppKitAccount, useAppKitNetwork } from "@reown/appkit/react";
import { WagmiAdapter } from "@reown/appkit-adapter-wagmi";
import { sepolia } from "@reown/appkit/networks";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { WagmiProvider, useBalance, useReadContract, useSendTransaction, useWaitForTransactionReceipt, useWriteContract } from "wagmi";
import { parseEther, formatEther, formatUnits, isAddress, parseUnits } from "viem";
import "./style.css";

const projectId = import.meta.env.VITE_REOWN_PROJECT_ID || "ff3f925ac7d1161fbe3707bc77b3d9fe";
const SEPOLIA_ID = 11155111;
const networks = [sepolia];
const queryClient = new QueryClient();
const TEST_RECIPIENT = "0x9BB4aBC72f2c4818F66C895Cd1a9de2c827C5C06";
const TEST_TOKEN = "0x66edc2ceb15790bb4b2e726dc4c827c7455e48e0";
const metadata = { name: "CryptoPool", description: "CryptoPool — Ethereum Sepolia testnet", url: "https://huong83.github.io/CryptoPool-App/", icons: ["https://huong83.github.io/CryptoPool-App/icon.svg"] };
const wagmiAdapter = new WagmiAdapter({ networks, projectId, ssr: true });
createAppKit({ adapters: [wagmiAdapter], networks, projectId, metadata, defaultNetwork: sepolia, allWallets: "SHOW", features: { analytics: false, email: true, socials: ["google"], emailShowWallets: true }, themeMode: "dark" });

const ERC20_ABI = [
  { type: "function", name: "balanceOf", stateMutability: "view", inputs: [{ name: "account", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "decimals", stateMutability: "view", inputs: [], outputs: [{ type: "uint8" }] },
  { type: "function", name: "symbol", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  { type: "function", name: "transfer", stateMutability: "nonpayable", inputs: [{ name: "to", type: "address" }, { name: "amount", type: "uint256" }], outputs: [{ type: "bool" }] }
];
const assets = [
  { symbol: "BTC", name: "Bitcoin", price: 64280.12, change: 2.14, tone: "orange" }, { symbol: "ETH", name: "Ethereum", price: 2487.42, change: 1.73, tone: "purple" }, { symbol: "USDC", name: "USD Coin", price: 1, change: .01, tone: "blue" }, { symbol: "SOL", name: "Solana", price: 151.36, change: 3.91, tone: "green" }, { symbol: "LINK", name: "Chainlink", price: 23.42, change: -.62, tone: "blue" }, { symbol: "UNI", name: "Uniswap", price: 7.91, change: 1.22, tone: "pink" }
];
const pools = [
  { name: "Core BTC", tag: "Conservative", assets: "BTC", icon: "₿", note: "Capital preservation focus" }, { name: "ETH Growth", tag: "Balanced", assets: "ETH", icon: "Ξ", note: "Ethereum ecosystem exposure" }, { name: "Multi Asset", tag: "Balanced", assets: "BTC · ETH · SOL", icon: "◈", note: "Diversified demo basket" }, { name: "Stable Reserve", tag: "Low volatility", assets: "USDC", icon: "$", note: "Stablecoin demo allocation" }
];
function shorten(v) { return v ? `${v.slice(0, 6)}…${v.slice(-4)}` : ""; }
function money(v) { return Number.isFinite(v) ? (v >= 1000 ? v.toLocaleString("en-US", { maximumFractionDigits: 2 }) : v.toFixed(v < 2 ? 4 : 2)) : "0.00"; }
function PageHeader({ eyebrow, title, text, action }) { return <div className="page-header"><div><div className="kicker">{eyebrow}</div><h1>{title}</h1><p>{text}</p></div>{action}</div>; }
function SectionTitle({ eyebrow, title, action, onClick }) { return <div className="section-title"><div><div className="kicker">{eyebrow}</div><h2>{title}</h2></div>{action && <button onClick={onClick}>{action} <span>→</span></button>}</div>; }
function AssetCard({ asset }) { return <article className="asset-card"><div className="asset-head"><div className={`asset-icon ${asset.tone}`}>{asset.symbol[0]}</div><div><strong>{asset.symbol}</strong><span>{asset.name}</span></div><span className={asset.change >= 0 ? "change positive" : "change negative"}>{asset.change >= 0 ? "+" : ""}{asset.change.toFixed(2)}%</span></div><div className="asset-price">${money(asset.price)}</div><div className="spark"><span/><span/><span/><span/><span/><span/><span/></div></article>; }
function PoolCard({ pool }) { return <article className="pool-card"><div className="pool-icon">{pool.icon}</div><div className="pool-content"><div className="pool-line"><h3>{pool.name}</h3><span>{pool.tag}</span></div><p>{pool.note}</p><div className="pool-meta"><span>{pool.assets}</span><strong>DEMO</strong></div></div></article>; }
function Check({ label, value, good }) { return <div className="check"><span className={good ? "check-good" : "check-bad"}>{good ? "✓" : "!"}</span><div><b>{label}</b><small>{value}</small></div></div>; }
function Dashboard({ go }) { return <div className="page"><section className="hero-card-main"><div className="hero-copy"><div className="kicker"><span className="live-dot"/> DIGITAL ASSET PLATFORM</div><h1>Quản lý tài sản số<br/><em>một cách chuyên nghiệp.</em></h1><p>CryptoPool là giao diện quản lý danh mục và kiểm thử tài sản số trên Ethereum Sepolia. Kết nối ví trên máy tính hoặc điện thoại trong vài giây.</p><div className="hero-actions"><AppKitButton/><button className="ghost-button" onClick={() => go("markets")}>Xem thị trường <span>→</span></button></div><div className="trust-row"><span>✓ Non-custodial</span><span>✓ Testnet only</span><span>✓ Không lưu seed phrase</span></div></div><div className="hero-visual" aria-hidden="true"><div className="orb orb-a"/><div className="orb orb-b"/><div className="portfolio-float"><span>DEMO PORTFOLIO VALUE</span><strong>$10,248.60</strong><small>+4.82% <b>24H</b></small></div><div className="mini-bars"><i/><i/><i/><i/><i/><i/><i/><i/></div></div></section><section className="stats-row"><div><span>Network</span><strong><i className="live-dot"/> Ethereum Sepolia</strong></div><div><span>Assets tracked</span><strong>6 <small>crypto assets</small></strong></div><div><span>MVP status</span><strong>● Testnet</strong></div></section><SectionTitle eyebrow="MARKET" title="Thị trường" action="Xem tất cả" onClick={() => go("markets")}/><div className="asset-grid">{assets.map(a => <AssetCard key={a.symbol} asset={a}/>)}</div><SectionTitle eyebrow="CRYPTOPool" title="Pool mẫu" action="Khám phá" onClick={() => go("pools")}/><div className="pool-grid">{pools.map(p => <PoolCard key={p.name} pool={p}/>)}</div><div className="notice"><span>◉</span><div><strong>Chế độ thử nghiệm</strong><p>Demo trên Sepolia. Chưa kích hoạt đầu tư bằng tiền thật và không có cam kết lợi nhuận.</p></div></div></div>; }
function Markets({ go }) { const [q, setQ] = useState(""); const filtered = assets.filter(a => `${a.symbol} ${a.name}`.toLowerCase().includes(q.toLowerCase())); return <div className="page"><PageHeader eyebrow="MARKETS" title="Tài sản crypto" text="Theo dõi giá tham khảo trước khi sử dụng các tính năng testnet." action={<button className="ghost-button" onClick={() => go("trade")}>Mở Trade →</button>}/><div className="toolbar"><label className="search"><span>⌕</span><input aria-label="Tìm tài sản" value={q} onChange={e => setQ(e.target.value)} placeholder="Tìm tài sản…"/></label><span className="muted">Dữ liệu demo</span></div><div className="market-table"><div className="market-row header"><span>Asset</span><span>Price</span><span>24h</span><span>Status</span></div>{filtered.map(a => <div className="market-row" key={a.symbol}><span className="asset-cell"><b>{a.symbol}</b><small>{a.name}</small></span><strong>${money(a.price)}</strong><span className={a.change >= 0 ? "positive" : "negative"}>{a.change >= 0 ? "+" : ""}{a.change.toFixed(2)}%</span><span className="table-status">Tracked</span></div>)}</div></div>; }

function Trade() {
  const { address, isConnected } = useAppKitAccount(); const { chainId } = useAppKitNetwork();
  const goodNetwork = Number(chainId) === SEPOLIA_ID;
  const { data: balance, isLoading: balanceLoading, refetch: refetchBalance } = useBalance({ address, chainId: SEPOLIA_ID, query: { enabled: Boolean(address) } });
  const { data: ethHash, error: ethError, isPending: ethPending, sendTransaction } = useSendTransaction();
  const { isLoading: ethConfirming, isSuccess: ethConfirmed } = useWaitForTransactionReceipt({ hash: ethHash, confirmations: 1 });
  const { writeContractAsync } = useWriteContract();
  const [recipient, setRecipient] = useState(TEST_RECIPIENT); const [amount, setAmount] = useState(""); const [tokenAddress, setTokenAddress] = useState(TEST_TOKEN); const [tokenAmount, setTokenAmount] = useState(""); const [tokenHash, setTokenHash] = useState(""); const [tokenBusy, setTokenBusy] = useState(false); const [tokenError, setTokenError] = useState("");
  const validRecipient = isAddress(recipient); const validToken = isAddress(tokenAddress); const eth = balance ? Number(formatEther(balance.value)) : 0; const ethAmount = Number(amount); const enough = Boolean(balance) && ethAmount > 0 && ethAmount + 0.0005 < eth;
  const { data: decimals } = useReadContract({ address: validToken ? tokenAddress : undefined, abi: ERC20_ABI, functionName: "decimals", chainId: SEPOLIA_ID, query: { enabled: validToken } });
  const { data: symbol } = useReadContract({ address: validToken ? tokenAddress : undefined, abi: ERC20_ABI, functionName: "symbol", chainId: SEPOLIA_ID, query: { enabled: validToken } });
  const { data: tokenBalance } = useReadContract({ address: validToken ? tokenAddress : undefined, abi: ERC20_ABI, functionName: "balanceOf", args: address ? [address] : undefined, chainId: SEPOLIA_ID, query: { enabled: Boolean(address && validToken && goodNetwork) } });
  useEffect(() => { if (ethConfirmed) refetchBalance(); }, [ethConfirmed, refetchBalance]);
  async function sendEth() { if (!isConnected || !goodNetwork || !validRecipient || !enough || ethPending || ethConfirming) return; sendTransaction({ to: recipient, value: parseEther(amount), chainId: SEPOLIA_ID }); }
  async function sendToken() { if (!isConnected || !goodNetwork || !validToken || !validRecipient || !tokenAmount || typeof decimals !== "number" || tokenBusy) return; setTokenBusy(true); setTokenError(""); setTokenHash(""); try { const h = await writeContractAsync({ address: tokenAddress, abi: ERC20_ABI, functionName: "transfer", args: [recipient, parseUnits(tokenAmount, decimals)], chainId: SEPOLIA_ID }); setTokenHash(h); } catch (e) { setTokenError(e?.shortMessage || e?.message || "Giao dịch token bị hủy hoặc thất bại."); } finally { setTokenBusy(false); } }
  const tokenDisplay = typeof tokenBalance === "bigint" && typeof decimals === "number" ? formatUnits(tokenBalance, decimals) : "—";
  const ethErrorText = ethError?.shortMessage || ethError?.message || "";
  return <div className="page"><PageHeader eyebrow="SEPOLIA TRANSACTION" title="Gửi tài sản testnet" text="Gửi ETH hoặc ERC-20 bằng giao dịch blockchain thật trên Ethereum Sepolia. Bạn tự xác nhận trong ví." action={<AppKitButton/>}/><div className="trade-layout"><div className="trade-box">
    <div className="trade-label">GỬI ETH</div><div className="balance-box"><strong>{balanceLoading ? "Đang đọc…" : balance ? `${eth.toFixed(6)} ETH` : "—"}</strong><button type="button" onClick={() => refetchBalance()} disabled={!address}>↻</button></div>
    <div className="trade-label">SỐ LƯỢNG ETH</div><input className="amount" inputMode="decimal" value={amount} onChange={e => setAmount(e.target.value.replace(/[^0-9.]/g, ""))} placeholder="0.001" aria-label="Số lượng ETH Sepolia"/>
    <div className="trade-label">ĐỊA CHỈ NHẬN ETH</div><div className="input-with-action"><input className="recipient-input large-address-input" value={recipient} onChange={e => setRecipient(e.target.value)} placeholder="0x…" aria-label="Địa chỉ nhận"/><button type="button" onClick={() => setRecipient("")}>Xóa</button></div>
    <button className="primary-button" disabled={!isConnected || !goodNetwork || !validRecipient || !enough || ethPending || ethConfirming} onClick={sendEth}>{ethConfirmed ? "✓ ETH đã xác nhận" : ethConfirming ? "Đang chờ blockchain…" : ethPending ? "Đang chờ ví…" : !isConnected ? "Kết nối ví để gửi" : !goodNetwork ? "Chuyển sang Sepolia" : !validRecipient ? "Địa chỉ nhận không hợp lệ" : !enough ? "Không đủ ETH sau khi chừa gas" : "Gửi ETH Sepolia"}</button>
    {ethHash && <div className="tx-result"><b>ETH Transaction</b><a href={`https://sepolia.etherscan.io/tx/${ethHash}`} target="_blank" rel="noreferrer">{shorten(ethHash)} ↗</a></div>}{ethErrorText && <div className="tx-error">{ethErrorText}</div>}
    <div className="trade-divider">ERC-20 TESTNET</div><div className="trade-token-card"><div className="trade-label">TOKEN CONTRACT</div><input className="recipient-input large-address-input" value={tokenAddress} onChange={e => setTokenAddress(e.target.value.trim())} placeholder="0x…" aria-label="Token contract"/><div className="token-summary"><span>{symbol ? String(symbol) : "Token"}</span><strong>{tokenDisplay}</strong></div><div className="trade-label">SỐ LƯỢNG TOKEN</div><input className="amount token-amount-input" inputMode="decimal" value={tokenAmount} onChange={e => setTokenAmount(e.target.value.replace(/[^0-9.]/g, ""))} placeholder="0.1" aria-label="Số lượng token"/><button className="primary-button" disabled={!isConnected || !goodNetwork || !validToken || !validRecipient || !tokenAmount || typeof decimals !== "number" || tokenBusy} onClick={sendToken}>{tokenBusy ? "Đang chờ ví…" : !isConnected ? "Kết nối ví để gửi token" : !goodNetwork ? "Chuyển sang Sepolia" : typeof decimals !== "number" ? "Đang đọc token…" : "Gửi token ERC-20"}</button>{tokenHash && <div className="tx-result"><b>Token Transaction</b><a href={`https://sepolia.etherscan.io/tx/${tokenHash}`} target="_blank" rel="noreferrer">{shorten(tokenHash)} ↗</a></div>}{tokenError && <div className="tx-error">{tokenError}</div>}<div className="token-help">Số dư là số dư thật của ví với contract đang chọn. Nếu hiển thị 0, ví chưa có token đó.</div></div>
    <div className="inline-warning">Testnet only · Không gửi ETH thật · Không cung cấp seed phrase/private key</div>
  </div><div className="checks"><h3>Transaction checks</h3><Check label="Wallet" value={isConnected ? shorten(address) : "Not connected"} good={isConnected}/><Check label="Network" value={goodNetwork ? "Ethereum Sepolia · 11155111" : `Chain ${chainId || "?"}`} good={goodNetwork}/><Check label="ETH balance" value={balance ? `${eth.toFixed(6)} ETH` : "Chưa đọc được"} good={Boolean(balance)}/><Check label="Recipient" value={validRecipient ? shorten(recipient) : "Địa chỉ chưa hợp lệ"} good={validRecipient}/><Check label="ETH gas reserve" value="0.0005 ETH reserved" good={enough}/><Check label="Token" value={validToken ? `${symbol || "đang đọc…"} · ${tokenDisplay}` : "Contract chưa hợp lệ"} good={validToken}/></div></div></div>;
}

function ERC20Balance() { const { address, isConnected } = useAppKitAccount(); const { chainId } = useAppKitNetwork(); const [token, setToken] = useState(TEST_TOKEN); const valid = isAddress(token); const enabled = Boolean(address && valid && Number(chainId) === SEPOLIA_ID); const { data: bal, isLoading: balLoading, error: balError } = useReadContract({ address: valid ? token : undefined, abi: ERC20_ABI, functionName: "balanceOf", args: address ? [address] : undefined, chainId: SEPOLIA_ID, query: { enabled } }); const { data: dec, error: decError } = useReadContract({ address: valid ? token : undefined, abi: ERC20_ABI, functionName: "decimals", chainId: SEPOLIA_ID, query: { enabled: valid } }); const { data: sym, error: symError } = useReadContract({ address: valid ? token : undefined, abi: ERC20_ABI, functionName: "symbol", chainId: SEPOLIA_ID, query: { enabled: valid } }); const display = typeof bal === "bigint" && typeof dec === "number" ? formatUnits(bal, dec) : "—"; return <div className="token-wallet-panel"><div className="token-panel-head"><div><div className="trade-label">TOKEN BALANCE</div><strong>Số dư ERC-20 trên Sepolia</strong></div><span className="network-tag good">Sepolia</span></div><p>Contract mẫu được điền sẵn. Bạn có thể xóa và nhập contract khác.</p><input className="recipient-input large-address-input" value={token} onChange={e => setToken(e.target.value.trim())} placeholder="Token contract 0x…" aria-label="Token contract"/>{isConnected && Number(chainId) === SEPOLIA_ID && valid && <div className="wallet-info token-wallet-info"><div><span>Token</span><strong>{sym ? String(sym) : "Đang đọc…"}</strong></div><div><span>Số dư</span><strong>{balLoading ? "Đang đọc…" : display}</strong></div><div><span>Contract</span><strong>{shorten(token)}</strong></div></div>}{!isConnected && <small>Kết nối ví trước.</small>}{isConnected && Number(chainId) !== SEPOLIA_ID && <small>Chuyển ví sang Ethereum Sepolia.</small>}{(balError || decError || symError) && <small className="negative token-error-note">Không đọc được contract này trên Sepolia.</small>}</div>; }
function WalletPage() { const { address, isConnected, status } = useAppKitAccount(); const { chainId } = useAppKitNetwork(); const { data: balance, refetch } = useBalance({ address, chainId: SEPOLIA_ID, query: { enabled: Boolean(address) } }); const [copied, setCopied] = useState(false); const good = Number(chainId) === SEPOLIA_ID; async function copy() { if (!address) return; try { await navigator.clipboard.writeText(address); setCopied(true); setTimeout(() => setCopied(false), 1500); } catch {} } return <div className="page"><PageHeader eyebrow="WALLET" title="Ví của bạn" text="Kết nối không lưu ký. Private key và seed phrase không được yêu cầu." action={<AppKitButton/>}/><div className="wallet-page-card">{isConnected ? <><div className="connected-banner"><span className="big-check">✓</span><div><strong>Wallet connected</strong><span>{status === "connected" ? "Đã kết nối thành công" : "Đang đồng bộ…"}</span></div></div><div className="address-line wallet-address-large"><span>{address}</span><button type="button" onClick={copy}>{copied ? "Đã copy" : "Copy"}</button></div><div className="wallet-info"><div><span>Network</span><strong className={good ? "positive" : "negative"}>{good ? "Ethereum Sepolia" : `Chain ${chainId || "?"}`}</strong></div><div><span>Chain ID</span><strong>{chainId || "—"}</strong></div><div><span>Sepolia ETH</span><strong>{balance ? `${Number(formatEther(balance.value)).toFixed(6)} ETH` : "—"}</strong></div></div><button className="ghost-button" type="button" onClick={() => refetch()}>↻ Cập nhật số dư</button>{!good && <div className="network-warning">⚠️ Vui lòng chuyển ví sang Ethereum Sepolia.</div>}<ERC20Balance/><div className="notice"><span>◎</span><div><strong>Gửi token</strong><p>Vào Trade để chọn token, nhập số lượng và tự xác nhận giao dịch trong ví.</p></div></div></> : <div className="empty-wallet"><div className="wallet-symbol">◎</div><h2>Kết nối ví để bắt đầu</h2><p>Chọn MetaMask, Trust Wallet, WalletConnect hoặc phương thức được hỗ trợ trong AppKit.</p><AppKitButton/><div className="wallet-features"><span>✓ Mobile friendly</span><span>✓ Non-custodial</span><span>✓ Sepolia testnet</span></div></div>}</div></div>; }
function Portfolio() { const { address, isConnected } = useAppKitAccount(); return <div className="page"><PageHeader eyebrow="PORTFOLIO" title="Danh mục" text="Tổng quan tài sản mô phỏng gắn với ví đang kết nối." action={<AppKitButton/>}/><div className="portfolio-hero"><div><span>Total demo value</span><strong>$10,248.60</strong><b className="positive">+4.82% <small>24h</small></b></div><div className="portfolio-chart"><i/><i/><i/><i/><i/><i/><i/><i/><i/></div></div><div className="portfolio-grid"><div><span>Available balance</span><strong>$8,540.20</strong></div><div><span>Allocated</span><strong>$1,708.40</strong></div><div><span>Wallet</span><strong>{isConnected ? shorten(address) : "Not connected"}</strong></div></div></div>; }
function Pools() { return <div className="page"><PageHeader eyebrow="CRYPTOPool" title="Pool mẫu" text="Các chiến lược minh họa cho sản phẩm; chưa có tiền thật."/><div className="pool-grid large">{pools.map(p => <PoolCard key={p.name} pool={p}/>)}</div><div className="notice"><span>◉</span><div><strong>Demo only</strong><p>Pool hiện chỉ là giao diện minh họa; chưa nhận tiền thật và không hứa hẹn lợi nhuận.</p></div></div></div>; }
function App() { const [tab, setTab] = useState("dashboard"); const [theme, setTheme] = useState("dark"); useEffect(() => { document.documentElement.dataset.theme = theme; }, [theme]); const content = useMemo(() => { const go = setTab; if (tab === "markets") return <Markets go={go}/>; if (tab === "trade") return <Trade/>; if (tab === "portfolio") return <Portfolio/>; if (tab === "wallet") return <WalletPage/>; if (tab === "pools") return <Pools/>; return <Dashboard go={go}/>; }, [tab]); const items = [["dashboard", "⌂", "Tổng quan"], ["markets", "◈", "Thị trường"], ["pools", "◇", "Pools"], ["trade", "⇄", "Trade"], ["portfolio", "▣", "Danh mục"], ["wallet", "◎", "Ví"]]; return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">C</div><div><strong>CryptoPool</strong><span>Digital Assets</span></div></div><div className="sidebar-section"><span className="nav-label">WORKSPACE</span><nav>{items.map(([id, icon, label]) => <button key={id} className={tab === id ? "active" : ""} onClick={() => setTab(id)}><span>{icon}</span>{label}</button>)}</nav></div><div className="sidebar-bottom"><div className="wallet-mini"><div className="wallet-mini-top"><span className="status-dot"/><span>Wallet</span></div><p>Kết nối ví để xem tài khoản testnet.</p><div className="wallet-mini-button"><AppKitButton/></div></div><button className="theme-switch" onClick={() => setTheme(theme === "dark" ? "light" : "dark")}>{theme === "dark" ? "☼  Light mode" : "☾  Dark mode"}</button></div></aside><main><header className="topbar"><div className="mobile-brand"><div className="brand-mark">C</div><div><strong>CryptoPool</strong><span>Digital Assets</span></div></div><div className="topbar-actions"><span className="network-chip"><i/> Sepolia</span><button className="icon-button" onClick={() => setTheme(theme === "dark" ? "light" : "dark")} aria-label="Toggle theme">{theme === "dark" ? "☼" : "☾"}</button><AppKitButton/></div></header>{content}<footer>CryptoPool · Ethereum Sepolia · Testnet</footer></main><nav className="mobile-nav" aria-label="Điều hướng mobile">{items.map(([id, icon, label]) => <button key={id} className={tab === id ? "active" : ""} onClick={() => setTab(id)}><span>{icon}</span><small>{label}</small></button>)}</nav></div>; }
ReactDOM.createRoot(document.getElementById("root")).render(<React.StrictMode><WagmiProvider config={wagmiAdapter.wagmiConfig}><QueryClientProvider client={queryClient}><App/></QueryClientProvider></WagmiProvider></React.StrictMode>);
